apiVersion: v2
name: dizquetv
description: A Helm chart for Kubernetes for deploying DizqueTV
type: application
version: 0.2.1
appVersion: "1.7.0"
maintainers:
  - name: vexorian
    url: https://github.com/vexorian
