{{- range .Values.pvcs }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .name }}
  namespace: {{ .namespace }}
  labels:
    app: {{ include "plex.name" . }}
spec:
  accessModes:
    {{- range .accessModes }}
    - {{ . }}
    {{- end }}
  resources:
    requests:
      storage: {{ .resources.requests.storage }}
  storageClassName: {{ .storageClassName }}
  volumeMode: {{ .volumeMode }}
  volumeName: {{ .volumeName }}
{{- end }}
