{{- if .Values.configPvc.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ default (printf "%s-config" (include "plex.fullname" .)) .Values.configPvc.name }}
  labels:
    {{- include "plex.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.configPvc.accessModes | nindent 4 }}
  {{- with .Values.configPvc.storageClassName }}
  storageClassName: {{ . }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.configPvc.size }}
{{- end }}
