{{if .Values.cfTunnel.enabled }}
---
apiVersion: networking.cfargotunnel.com/v1alpha1
kind: TunnelBinding
metadata:
  name: {{ include "jellyfinvue.fullname" . }}
  labels:
    {{- include "jellyfinvue.labels" . | nindent 4 }}
subjects:
  - name: {{ include "jellyfinvue.fullname" . }}
    spec:
      fqdn: {{ .Values.cfTunnel.fqdn }}
tunnelRef:
  kind: ClusterTunnel
  name: {{ .Values.cfTunnel.tunnelName }}
{{- end }}
